// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Apollo = require("./Apollo.bs.js");
var PostAddNext = require("./PostAddNext.bs.js");
var ReasonReactRouter = require("reason-react/src/ReasonReactRouter.js");
var FavoriteColorsForm = require("./FavoriteColorsForm.bs.js");
var ReactHooks = require("@apollo/react-hooks");

function App(Props) {
  var message = Props.message;
  var url = ReasonReactRouter.useUrl(undefined, /* () */0);
  var match = url[/* path */0];
  var tmp;
  var exit = 0;
  if (match) {
    switch (match[0]) {
      case "fav-colors" : 
          if (match[1]) {
            exit = 1;
          } else {
            tmp = React.createElement(FavoriteColorsForm.make, { });
          }
          break;
      case "new-post" : 
          if (match[1]) {
            exit = 1;
          } else {
            tmp = React.createElement(PostAddNext.make, { });
          }
          break;
      default:
        exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = React.createElement("p", {
          className: "App-intro"
        }, "Say hello to ReForm");
  }
  return React.createElement(ReactHooks.ApolloProvider, {
              client: Apollo.client,
              children: React.createElement("div", {
                    className: "App"
                  }, React.createElement("div", {
                        className: "App-header"
                      }, React.createElement("img", {
                            className: "App-logo",
                            alt: "logo",
                            src: "https://astrocoders.com/panel.png"
                          }), React.createElement("h2", undefined, message)), React.createElement("h1", undefined, "ReFormNext demo"), React.createElement("a", {
                        href: "/new-post"
                      }, "New post form demo "), React.createElement("br", undefined), React.createElement("a", {
                        href: "/fav-colors"
                      }, "Form with array field demo"), React.createElement("div", {
                        style: {
                          padding: "100px"
                        }
                      }, tmp))
            });
}

var make = App;

exports.make = make;
/* react Not a pure module */
