// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.bs.js");
var Curry = require("rescript/lib/js/curry.js");
var ReSchema = require("reschema/src/ReSchema.bs.js");

function get(state, field) {
  if (field) {
    return state.age;
  } else {
    return state.email;
  }
}

function set(state, field, value) {
  if (field) {
    return {
            email: state.email,
            age: value
          };
  } else {
    return {
            email: value,
            age: state.age
          };
  }
}

var ProfileLenses = {
  get: get,
  set: set
};

Jest.test("should validate a correct record", (function (param) {
        var ProfileValidation = ReSchema.Make({
              set: set,
              get: get
            });
        var schema = /* Schema */{
          _0: Curry._2(ProfileValidation.Validation.$plus, Curry._3(ProfileValidation.Validation.email, undefined, undefined, /* Email */0), Curry._6(ProfileValidation.Validation.$$int, 18, undefined, undefined, undefined, undefined, /* Age */1))
        };
        return Jest.Expect.toBe(/* Errors */{
                    _0: []
                  }, Jest.Expect.expect(Curry._3(ProfileValidation.validate, undefined, {
                            email: "teste@mail.com",
                            age: 18
                          }, schema)));
      }));

exports.ProfileLenses = ProfileLenses;
/*  Not a pure module */
