// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");

function handleChange(handleChange$1, $$event) {
  return Curry._1(handleChange$1, $$event.target.value);
}

function handleSubmit(handleSubmit$1, $$event) {
  $$event.preventDefault();
  return Curry._1(handleSubmit$1, undefined);
}

exports.handleChange = handleChange;
exports.handleSubmit = handleSubmit;
/* No side effect */
