// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";

function handleChange(handleChange$1, $$event) {
  return Curry._1(handleChange$1, $$event.target.value);
}

function handleSubmit(handleSubmit$1, $$event) {
  $$event.preventDefault();
  return Curry._1(handleSubmit$1, undefined);
}

export {
  handleChange ,
  handleSubmit ,
  
}
/* No side effect */
